name: Hello World Training Workflow

on: 
  workflow_dispatch: # Це тригер для ручного запуску

jobs:
  greet-and-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello using Environment Variable
        env:
          GREETING: "Hello World! Danya was here."
        run: |
          echo "$GREETING"
          echo "This workflow was triggered manually."

      - name: List files
        run: ls -la
